env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  'no-use-before-define': [0]
  '@typescript-eslint/no-use-before-define': [1]
