---
version: "3.8"

services:
  # ----
  # Main
  # ----

  # auth:

  db:
    volumes:
      - /var/lib/postgresql/data
      - ./volumes/db/dev/dev-data.sql:/docker-entrypoint-initdb.d/dev-data.sql

  frontend:
    environment:
      REACT_APP_TEST_USER_EMAIL: test@test.com
      REACT_APP_TEST_USER_PASSWORD: password
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/yarn.lock:/app/yarn.lock

  # kong:

  meta:
    ports:
      - 5555:8080

  # realtime:

  # rest:

  storage:
    volumes:
      - /var/lib/storage

  # -------------
  # Microservices
  # -------------

  table-parser:
    environment:
      DEBUG: 'true'
      HTTPX_LOG_LEVEL: debug
    # # For interactive debugging
    # command: 'python -m pdb -c continue -m table_parser'
    # stdin_open: true
    # tty: true
    volumes:
      - ./table-parser:/app

  function-server:
    command: ["uvicorn", "function_server.app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    volumes:
      - ./function-server:/app

  # ----------
  # Monitoring
  # ----------

  # grafana:

  # loki:

  # ---------
  # Debugging
  # ---------

  # graphiql:
  #   container_name: graphiql
  #   build: ./graphiql
  #   ports:
  #     - 8000:8000

  mail:
    container_name: supabase-mail
    image: inbucket/inbucket:stable
    ports:
      - '2500:2500' # SMTP
      - '9000:9000' # web interface
      - '1100:1100' # POP3

  studio:
    container_name: supabase-studio
    image: supabase/studio:latest
    restart: unless-stopped
    ports:
      - ${STUDIO_PORT}:3000/tcp
    environment:
      SUPABASE_URL: ${KONG_URL}
      STUDIO_PG_META_URL: ${META_URL}
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
