/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TableParserMessage =
  | {
      status: "ERROR";
      error: string;
    }
  | {
      status: "UPLOAD_SUCCESS";
    }
  | {
      status: "PREPARE_UPLOAD";
      file: {
        name: string;
        nSlices: number;
        accessToken: string;
        userId: string;
        contentType: string;
      };
    }
  | {
      status: "SAVED";
      uploadedFileId: string;
      objectKey: string;
    }
  | {
      status: "REQUEST_TABLE_UPDATE";
      accessToken?: string;
      objectKey?: string;
    }
  | {
      status: "TABLE_UPDATE";
      tableData: {
        rowData: {
          [k: string]: unknown;
        }[];
        columnDefs: {
          field: string;
        }[];
      };
    };
