# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2022-03-09T04:22:35+00:00

from __future__ import annotations

from typing import Any, Optional
from uuid import UUID

from pydantic import BaseModel


class Model(BaseModel):
    class Config:
        allow_population_by_field_name = True

    __root__: Optional[Any] = None


class UploadedFiles(BaseModel):
    class Config:
        allow_population_by_field_name = True

    id: Optional[UUID] = None
    file_name: Optional[str] = None
    owner: Optional[UUID] = None
    object_key: Optional[str] = None
