# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2022-03-08T22:47:40+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Optional
from uuid import UUID

from pydantic import BaseModel, Field, constr


class Model(BaseModel):
    class Config:
        allow_population_by_field_name = True

    __root__: Any


class Account(BaseModel):
    class Config:
        allow_population_by_field_name = True

    id: int = Field(..., description='Note:\nThis is a Primary Key.<pk/>')
    email: constr(max_length=255)
    encrypted_password: constr(max_length=255)
    created_at: str
    updated_at: str


class Blog(BaseModel):
    class Config:
        allow_population_by_field_name = True

    id: int = Field(..., description='Note:\nThis is a Primary Key.<pk/>')
    owner_id: int = Field(
        ...,
        description="Note:\nThis is a Foreign Key to `account.id`.<fk table='account' column='id'/>",
    )
    name: constr(max_length=255)
    description: Optional[constr(max_length=255)] = None
    created_at: str
    updated_at: str


class Status(Enum):
    pending = 'PENDING'
    released = 'RELEASED'


class BlogPost(BaseModel):
    class Config:
        allow_population_by_field_name = True

    id: Optional[UUID] = Field(
        'extensions.uuid_generate_v4()',
        description='Note:\nThis is a Primary Key.<pk/>',
    )
    blog_id: int = Field(
        ...,
        description="Note:\nThis is a Foreign Key to `blog.id`.<fk table='blog' column='id'/>",
    )
    title: constr(max_length=255)
    body: Optional[constr(max_length=10000)] = None
    status: Status
    created_at: str
    updated_at: str


class UploadedFiles(BaseModel):
    class Config:
        allow_population_by_field_name = True

    id: Optional[UUID] = 'extensions.uuid_generate_v4()'
    file_name: Optional[str] = None
    owner: Optional[UUID] = None
    object_id: Optional[UUID] = Field(
        None,
        description="Note:\nThis is a Foreign Key to `objects.id`.<fk table='objects' column='id'/>",
    )
